src/app.ts
src/availability/middleware/service.availability.ts
src/feature.flag.ts
src/model/template.paths.ts
src/properties.ts
src/routes/routes.ts
test/availability/middleware/service.availability.spec.unit.ts
test/global.setup.ts
views/service-offline.html

Similar to promise to file - created middleware to load an alternative template if the flag is set.

BI-4007 service offline landing page

---

views/index.html
views/layout.html

Fixes problem with p tags in the body not picking up govuk stylings. Also replaced prototype footer with the companies house standard one

BI-3878 updating how web app uses cdn resources

---

.gitignore
.gitmodules
Makefile
package-lock.json
package.json
src/app.ts
src/constants.ts
src/logger.ts
src/model/objection.company.profile.ts
src/services/company.profile.service.ts
src/utils/api.enumerations.ts
src/utils/date.formatter.ts
test/global.setup.ts
test/services/company.profile.service.spec.unit.ts
test/utils/api.enumerations.spec.unit.ts
test/utils/date.formatter.spec.unit.ts

Adding company profile service to get the company profile from CHS
Also added the api-enumerations submodule for translating some company profile values

BI-4030 Adding company profile service

---

test/availability/middleware/service.availability.spec.unit.ts
test/routes/routes.spec.unit.ts
views/company-number.html
views/confirm-company.html
views/index.html
views/layout.html

Jira ticket at: https://companieshouse.atlassian.net/browse/BI-3883

Updated text on start page and fixed links in current pages

---

package-lock.json
package.json

My IDE also re-ordered the dependencies alphabetically

BI-3957 Adding js-yaml library , used for parsing api-enumerations

---

views/confirm-company.html
views/layout.html

Changed gov uk table to summary list as we have done for previous projects.

bi-4134 template compnents not right

---

test/routes/routes.spec.unit.ts
views/confirm-company.html
views/enter-information.html

Jira ticket at: https://companieshouse.atlassian.net/browse/BI-4232

BI-4232 replaced get call with href and changed page heading on enter-information page

---

src/modules/sdk/objections/service.ts
src/services/objections.service.ts
test/services/objections.service.spec.unit.ts

Stubbed two service methods api and sdk and stubbed a test

OBJ-68 stub for adding attachment

---

src/controllers/company.number.controller.ts
src/controllers/confirm.company.controller.ts
src/routes/routes.ts
views/confirm-company.html
views/enter-information.html

Tried to make the route names a bit clearer by having get/post instead of 'route'
and noticed backlinks were'n right so fixed them

OBJ-45 Changed route names to get/post and fixed back links

---

src/app.ts
src/controllers/error.controller.ts
src/model/page.urls.ts
src/model/template.paths.ts
test/controller/error.controller.spec.unit.ts
views/error.html

Jira ticket at: https://companieshouse.atlassian.net/browse/OBJ-44

OBJ-44 Created error handler controller, unit tests and error page

---

src/controllers/remove.document.controller.ts
test/controller/remove.document.controller.spec.unit.ts

Adding error handling for api call errors and page render errors

OBJ-11 add error handling to remove document page

---

src/controllers/document_upload/document.upload.controller.ts
src/model/error.messages.ts
test/controller/document_upload/document.upload.controller.spec.unit.ts

Error message code to handle 415 status error from the api.

OBJ-101 error handling for invalid file types

---

src/app.ts
src/controllers/download.attachment.landing.controller.ts
src/model/page.urls.ts
src/model/template.paths.ts
src/routes/routes.ts
test/controller/download.attachment.landing.controller.spec.unit.ts
views/download.html

Jira ticket at https://companieshouse.atlassian.net/browse/OBJ-193

OBJ-193 adding download landing page and controller

---

src/controllers/check.your.answers.controller.ts
src/modules/sdk/objections/service.ts
src/services/objection.service.ts
test/modules/sdk/objections/service.spec.unit.ts
test/services/objection.service.spec.unit.ts

Also updated the objections service to call the sdk for download.

OBJ-205 Adding stub for api download call

---

views/file-error.html

Modelled on the extensions example - a generic  file error template ready to take a forbidden error message.

OBJ-195 Generic file error template

---

src/modules/sdk/objections/service.ts
src/services/objection.service.ts

Changed to debug logging in SDK service and info logging in objections service

Standardised logging in SDK service and objections service classes

---

views/confirmation.html

Removed illegal whitespace and tested link still works.

OBJ-234 removed whitespace

---

src/controllers/objecting.entity.name.controller.ts
src/middleware/authentication.middleware.ts
src/model/page.urls.ts
src/model/template.paths.ts
src/routes/routes.ts
test/controller/objecting.entity.name.controller.spec.unit.ts
test/middleware/authentication.middleware.spec.unit.ts
test/routes/routes.spec.unit.ts
views/company-number.html
views/index.html
views/objecting-entity-name.html

Story at https://companieshouse.atlassian.net/browse/OBJ-49
Adding the empty post method and the error variables in the HTML in preparation for the validation that will be done in OBJ-50.
Will need to let testers know before this is merged as it will break all of their tests.

OBJ-49 creating objecting entity name screen

---

src/controllers/check.your.answers.controller.ts
src/modules/sdk/objections/types.ts
test/controller/check.your.answers.controller.spec.unit.ts
views/check-your-answers.html

User information required on check answers screen.
email address
full name
share/divulge information

OBJ-249 check application user details

---

test/middleware/service.availability.middleware.spec.unit.ts
test/routes/routes.spec.unit.ts
views/index.html

obj-186 ammended landng page text

---

views/index.html

Added banner by removing blank text override.

OBJ-137 Added banner text by removing blank override

---

views/layout.html

OBJ-137 Missed some banner text

---

views/check-your-answers.html
views/company-number.html
views/confirm-company.html
views/document-upload.html
views/enter-information.html
views/index.html
views/objecting-entity-name.html
views/remove-document.html

Jira ticket at https://companieshouse.atlassian.net/browse/OBJ-260
Also readded the blank header into the index template as that was preventing redirection to the companies house home page when the govuk link is pressed.

OBJ-260 removing data events from continue buttons and company number input 

---

views/document-upload.html

Document upload screen text amendments.

obj-189 bullet points chnaged on document upload screen

---

src/app.ts
views/company-number.html
views/index.html
views/layout.html
views/objecting-entity-name.html

story at https://companieshouse.atlassian.net/browse/OBJ-259
requires https://github.com/companieshouse/chs-configs/pull/1219 to go in at the same time. Devs will also need to add these variables to their vagrant envs to prevent crashing.

OBJ-259 enabling matomo tracking and adding data events

---

src/controllers/enter.information.controller.ts
src/controllers/objecting.entity.name.controller.ts
test/controller/enter.information.controller.spec.unit.ts
test/routes/routes.spec.unit.ts
test/services/objection.session.service.spec.unit.ts
views/enter-information.html

Jira ticket at https://companieshouse.atlassian.net/browse/OBJ-282

OBJ-282 adding functionality to render enter information page with existing reason if it exists

---

views/objecting-entity-name.html

Jira ticket at https://companieshouse.atlassian.net/browse/OBJ-294

OBJ-294 fixing no focus on divulge info radio button error

---

src/controllers/check.your.answers.controller.ts
src/controllers/objecting.entity.name.controller.ts
src/modules/sdk/objections/types.ts
src/services/objection.service.ts
test/controller/check.your.answers.controller.spec.unit.ts
test/controller/company.number.controller.spec.unit.ts
test/controller/confirm.company.spec.unit.ts
test/controller/enter.information.controller.spec.unit.ts
test/controller/objecting.entity.name.controller.spec.unit.ts
test/modules/sdk/objections/service.spec.unit.ts
test/routes/routes.spec.unit.ts
test/services/objection.service.spec.unit.ts
test/services/objection.session.service.spec.unit.ts
views/check-your-answers.html

Updated the created_by returned for GET.

OBJ-299 Changing ObjectionCreate vars from camel case to snake case

---

src/controllers/company.number.controller.ts

Sonar was still complaining the regex was too complicated, so further simplified the regex

OBJ-302 further regex enhancements

---

src/controllers/company.number.controller.ts

Updating company number regex based on Sonar report to prevent a security vulnerability

OBJ-302 Updating company number regex for security vulnerability

---

test/routes/routes.spec.unit.ts
views/index.html

added "What is The Gazette?" details element to the landing page with links.

OBJ-329 amending objections landing page

---

test/routes/routes.spec.unit.ts
views/check-your-answers.html
views/confirmation.html
views/document-upload.html
views/enter-information.html

Made sure tab title matches the list specified for the MVP on ther ticket:
https://companieshouse.atlassian.net/browse/OBJ-149

OBJ-149 Update tab titles

---

src/app.ts
src/controllers/error.controller.ts
src/model/error.messages.ts
src/model/template.paths.ts
test/controller/error.controller.spec.unit.ts
views/page-not-found.html

Added new page template, test and error function for 404 errors.

OBJ-111 add page not found screen for 404 errors

---

src/model/error.messages.ts
test/controller/remove.document.controller.spec.unit.ts

Updating the validation message text for removing a document page

OBJ-14 Fixing remove doc validation wording

---

jest.config.js

excluding the src/bin folder from the test coverage results

Excluding src/bin from test coverage

---

src/controllers/check.your.answers.controller.ts
src/controllers/confirmation.controller.ts
test/controller/check.your.answers.controller.spec.unit.ts
test/controller/confirmation.controller.spec.unit.ts

Also correctly handle any errors when submitting objections

OBJ-233 Remove objection id from web session after submission

---

src/controllers/document_upload/document.upload.controller.ts
test/controller/document_upload/document.upload.controller.spec.unit.ts
test/routes/routes.spec.unit.ts
views/document-upload.html
views/includes/document-upload-file-picker.html

Changed the word 'Add' to 'Upload' in the html templates including the button text. Updated the the strategy files and tests.

OBJ-364 Amend upload page text

---

package.json
src/controllers/confirm.company.controller.ts
src/services/company.filing.history.service.ts
src/services/company.profile.service.ts
test/controller/confirm.company.controller.spec.unit.ts
test/services/company.filing.history.service.spec.unit.ts
test/services/company.profile.service.spec.unit.ts

Remove ch-sdk-node and replace with api-sdk-node.

OBJ-325/393 Updated to use ap-sdk-node library

---

src/app.ts
views/document-upload.html
views/layout.html

Changed CDN_URL constant in the app to be assetPath as that's what the govuk template we're extending uses to find the image path.

Getting Companies House favicon to appear in tab

---

src/controllers/enter.information.controller.ts

If error is thrown retrieving values from session, pass error to next function

pass potential errors to next function

---

views/confirmation.html

OBJ-463 Amend objection application submitted text

---

README.md

OBJ-466 Update README.md

---

views/document-upload.html

Added clarification text to document upload screen.
Covers: https://companieshouse.atlassian.net/browse/OBJ-480

Added text onto document-upload screen

---

src/controllers/objector.organisation.controller.ts
views/includes/piwik-scripts.html
views/objector-organisation.html

Adding matomo events for the who is applying to object screen
Resolves: [OBJ-443](https://companieshouse.atlassian.net/browse/OBJ-443)

Adding matomo events for 'Who is applying to object?' screen

---

src/app.ts
src/controllers/index.controller.ts
src/middleware/authentication.middleware.ts
test/global.setup.ts
test/middleware/authentication.middleware.spec.unit.ts

Resolves: [BI-7557](https://companieshouse.atlassian.net/browse/BI-7557) 
Adding logic to enable feature flag for new objector journey, also adding tests for appropriate objector journey when toggling feature flag on and off.

Creating feature flag for objector journey

---

views/notice-expired.html

Updated the "Contact Us" link to match accessibility spec given by DAC

Updated contact us link to match DAC specs

---

views/check-your-answers.html

Removed text from showing or being read by text to speech
based on DAC recommendation

Removing text from check answers page

---

views/index.html

Added time out text to the start of the journey based on DAC recommendations

Added timeout text to start screen

---

views/check-your-answers.html

Changing the display text from _Full name or organisation name_ to _Name_
Resolves: [OBJ-436](https://companieshouse.atlassian.net/browse/OBJ-436)

Amend name on the Check your objection application screen

---

src/controllers/check.your.answers.controller.ts
src/controllers/confirm.company.controller.ts
src/controllers/confirmation.controller.ts
src/controllers/document_upload/document.upload.controller.ts
src/controllers/document_upload/html.upload.responder.strategy.ts
src/controllers/enter.information.controller.ts
src/controllers/error.controller.ts
src/controllers/index.controller.ts
src/controllers/no.strike.off.controller.ts
src/controllers/notice.expired.controller.ts
src/controllers/objecting.entity.name.controller.ts
src/controllers/objector.organisation.controller.ts
src/controllers/remove.document.controller.ts
test/controller/document_upload/html.upload.responder.strategy.spec.unit.ts
test/controller/objecting.entity.name.controller.spec.unit.ts

Adding templateName variable onto all renders of the screens to show correctly in Matomo. Currently it is showing 'undefined' for the page titles and any events recorded.
Resolves: [BI-7551](https://companieshouse.atlassian.net/browse/BI-7551)

Adding templateName variable onto all renders of the screens to show correctly in Matomo

---

views/index.html

Added matomo event tracking to the start page of the service.
Resolves https://companieshouse.atlassian.net/browse/BI-7786

Added matomo events to start page

---

views/document-upload.html
views/includes/document-upload-file-list.html

Resolves: [BI-7797](https://companieshouse.atlassian.net/browse/BI-7797)

Adding matomo events onto the remove and cancel links for document upload

---

views/check-your-answers.html

Resolves: [BI-7798](https://companieshouse.atlassian.net/browse/BI-7798)

Adding matomo events onto all change links on the check your answers screen

---

views/company-number.html

Adding the data-event-id for matomo tracking in check company number page
Resolves: [BI-7795](https://companieshouse.atlassian.net/browse/BI-7795)

Adding the data-event-id for matomo tracking in check company number page

---

views/index.html

Resolves: [BI-7679](https://companieshouse.atlassian.net/browse/BI-7679)

Amending the link text on the start page to make it more descriptive for screen readers

---

src/constants.ts
views/accessibility-statement.html
views/check-your-answers.html
views/company-number.html
views/confirm-company.html
views/confirmation.html
views/document-upload.html
views/enter-information.html
views/error.html
views/index.html
views/no-strike-off.html
views/notice-expired.html
views/objecting-entity-name.html
views/objector-organisation.html
views/page-not-found.html
views/remove-document.html
views/service-offline.html

Resolves: [BI-7676](https://companieshouse.atlassian.net/browse/BI-7676)

Amending the page titles to be GDS compliant

---

views/check-your-answers.html

Remove duplicated information to improve the voice user experience
Resolves: [BI-7677](https://companieshouse.atlassian.net/browse/BI-7677)

Remove duplicated information to improve the voice user experience

---

src/app.ts
src/constants.ts
src/controllers/index.controller.ts
src/controllers/objecting.entity.name.controller.ts
src/middleware/authentication.middleware.ts
src/validation/index.ts
test/controller/index.controller.spec.unit.ts
test/controller/objecting.entity.name.controller.spec.unit.ts
test/global.setup.ts
test/middleware/authentication.middleware.spec.unit.ts
test/routes/routes.spec.unit.ts

Resolves: [BI-7662)](https://companieshouse.atlassian.net/browse/BI-7662)

Remove objector organisation journey feature flag

---

src/controllers/objecting.entity.name.controller.ts
src/modules/sdk/objections/types.ts
test/controller/objecting.entity.name.controller.spec.unit.ts
test/modules/sdk/objections/service.spec.unit.ts
test/routes/routes.spec.unit.ts
test/services/objection.service.spec.unit.ts
test/services/objection.session.service.spec.unit.ts

Resolves: [BI-7664](https://companieshouse.atlassian.net/browse/BI-7664)

Changing objector field to be mandatory

---

views/confirm-company.html

Resolve [BI-7796](https://companieshouse.atlassian.net/browse/BI-7796)

Add event to link on 'Confirm this is the correct company' page

---

src/controllers/company.number.controller.ts
src/routes/routes.ts

Add page name to the events and errors on "What is the company number?" page
Resolves: [BI-7936](https://companieshouse.atlassian.net/browse/BI-7936)

Adding the class name in the matomo event and error tagging

---

package.json

Resolves https://companieshouse.atlassian.net/browse/BI-8188

Updated trim-newlines to fix security vulnerability

---

package-lock.json

Bump `glob-parent` and `normalize-url` transient dependency
Part of [BI-8520](https://companieshouse.atlassian.net/browse/BI-8520)

Bump glob-parent and normalize-url transient dependency

---

src/controllers/index.controller.ts
test/controller/index.controller.spec.unit.ts

Resolve [BI-9219](https://companieshouse.atlassian.net/browse/BI-9219)
Add redirect logic to integrate gov.uk start page

Add logic into strike off objections to integrate gov.uk start page

---

src/controllers/change.answers.controller.ts
src/utils/request.util.ts

Adding in an allow list to check url is valid on redirect in change your answers page

wip- adding in an allow list to check url

---

src/modules/sdk/objections/axios.client.ts
src/services/company.filing.history.service.ts
src/services/company.profile.service.ts
test/controller/document.download.landing.controller.spec.unit.ts
test/services/company.filing.history.service.spec.unit.ts
test/services/company.profile.service.spec.unit.ts
views/download.html

Jira: https://companieshouse.atlassian.net/browse/DEBT-1740
Changed throw error to remove major vulnerabilities 
changed meta http-equiv="refresh" to javascript

fix major security vulnerabilities in strike off objections

---

src/constants.ts
src/controllers/signout.controller.ts
src/middleware/common.variables.middleware.ts
src/model/page.urls.ts
src/model/template.paths.ts
src/routes/routes.ts
src/services/company.filing.history.service.ts
src/services/company.profile.service.ts
src/utils/properties.ts
test/controller/document.download.landing.controller.spec.unit.ts
test/controller/signout.controller.spec.unit.ts
test/global.setup.ts
test/middleware/common.variables.middleware.unit.ts
test/services/company.filing.history.service.spec.unit.ts
test/services/company.profile.service.spec.unit.ts
views/includes/back-link.html
views/includes/continue-button.html
views/signout.html

This resolves [BI-11207](https://companieshouse.atlassian.net/browse/BI-11207) and [BI-11399](https://companieshouse.atlassian.net/browse/BI-11399)
The following has been added
- Sign out bar throughout the journey
- Sign out confirmation page

BI-11207 & BI-11399 add sign out feature

---

views/signout.html

Resolves: [BI-11638](https://companieshouse.atlassian.net/browse/BI-11637)
- Amend page description text to read to the correct company name for screen reader

amend description to read to the correct company name

---

views/layout.html

jira ticket: https://companieshouse.atlassian.net/browse/BI-12039
Implement idle sign out in the objections service

implement script which causes idle signout

---

terraform/groups/ecs-service/locals.tf

Updated local.tf to have correct variable for log_level

corrected log_level var

---

jest.config.js
package-lock.json
package.json

Bumps up library versions for `api-sdk-node` and `ch-structured-logging-node`

Chore: Bump up library versions for `api-sdk-node` and `ch-structured-logging-node`

---

package-lock.json
package.json
src/middleware/authentication.middleware.ts
test/middleware/authentication.middleware.spec.unit.ts
tsconfig.json

- bump package versions to upgraded versions

Chore/CC-876: Bump library versions

---

package-lock.json
package.json
src/controllers/document_upload/http.request.file.uploader.ts
src/modules/sdk/objections/types.ts

Updated code to be compatible for latest version of Busboy 1.6.0 and update few dependencies

Update to remove vulnerabilities

---

test/middleware/service.availability.middleware.spec.unit.ts
test/routes/routes.spec.unit.ts
views/index.html

Jira ticket: https://companieshouse.atlassian.net/browse/BI-14152
Update to strike off objection start page to reflect changes to objects due to ESO. Changes to text only

update start page to reflect changes due to ESO
