companieshouse/strike-off-objections-web

package-lock.json, package.json, src/app.ts, src/logger.ts, src/properties.ts, src/routes/routes.ts, test/availability/middleware/service.availability.spec.unit.ts, test/routes/routes.spec.unit.ts, tsconfig.json
Adding the ch-structured-logging-node logger
needed to add esModuleInterop to the tsconfig which in turn changed the way the express import is made in app.ts. The tsconfig flag is to allow mixing of js and typescript exports from modules (or something like that!)
=> BI-4030 Adding logger functionality

package-lock.json, package.json, src/controllers/company.number.controller.ts, src/controllers/confirm.company.controller.ts, src/model/objection.company.profile.ts, src/routes/routes.ts, src/services/company.profile.service.ts, src/services/objections.session.service.ts, test/controller/company.number.controller.spec.unit.ts, test/controller/confirm.company.spec.unit.ts, test/global.setup.ts, test/routes/routes.spec.unit.ts, test/services/objections.session.service.spec.unit.ts, tslint.json
test was hanging due to 2 things:
a) needed to mock redis out with jest.mock("ioredis");
b) the route function was falling into the else block as the session had no data and it needed to return something after it had logged the error otherwise it just hangs. I've added return next() to get the test to pass but unsure if this will work in real life (haven't run it). We need to implement the generic error screen so we can call next(new Error("blah"));  
added the data block to the session in the mock implementation to get past the 'if' in the controller. I'll look into whether we can make that mock importable, but for the time being just do similar in each test.
tidied up a few things, the getDummyProfile function in the test was returning a function which was passed into the template so …
=> BI-4032 Fixes for confirm company test

src/controllers/document_upload/document.upload.controller.ts, src/controllers/document_upload/http.request.file.uploader.ts
Making the upload file callback function return Promise<void> so they can be called with await in uploadFile. This should mean if they return a reject (as opposed to resolve) the reject error won't be lost.
=> OBJ-70 Making the upload file callback function return Promise<void>

src/model/error.messages.ts
Comment on Jira ticket:
Oceanne & Emma said the error message is to read:  
‘There is a problem
Add a document to support your objection’
Changed message.
=> OBJ-12 changed message output for upoad error

src/services/objection.service.ts, src/services/objection.session.service.ts, test/modules/sdk/objections/service.spec.unit.ts
Adding extra tests to check return values and that correct api urls are used
also removed duplications from objection.service.ts
=> OBJ-144 Improve sdk service tests

src/controllers/document_upload/document.upload.controller.ts, src/controllers/document_upload/http.request.file.uploader.ts, src/modules/sdk/objections/service.ts, src/services/objection.service.ts, test/modules/sdk/objections/service.spec.unit.ts, test/services/objection.service.spec.unit.ts
Addresses the specific issue identified in https://companieshouse.atlassian.net/browse/OBJ-146 but I've created a new story for discussion - and implementation - to investigate how we deal with user-entered text appearing in JSON output in the logs. See https://companieshouse.atlassian.net/browse/OBJ-151.
=> Obj 146 sanitise logs

src/controllers/confirm.company.controller.ts, src/controllers/enter.information.controller.ts, src/routes/routes.ts, test/controller/confirm.company.spec.unit.ts, test/controller/enter.information.controller.spec.unit.ts, views/confirm-company.html
This is to prevent a new objection being created if the user goes back to the enter information page to change their reason.
Jira ticket at https://companieshouse.atlassian.net/browse/OBJ-106
=> Moving create objection call to confirm company post method

src/controllers/objecting.entity.name.controller.ts, test/controller/objecting.entity.name.controller.spec.unit.ts, views/objecting-entity-name.html
Added values to name page, so that they are held when an error is displayed.
=> obj-265 ensure values are kept on error page

views/check-your-answers.html
Previous to this change, 
`<span class="govuk-summary-list__actions"></span>`
 
was getting added to the list. Now,
```
<dd class="govuk-summary-list__actions">
<a class="govuk-link" href="">
    </a>
</dd>
```
is added, but shouldn't violate the accessibility rule since `<dd>` is allowed as a child element.
=> OBJ-292 Suppress addition of 'span' elements in list

src/controllers/enter.information.controller.ts, src/controllers/remove.document.controller.ts, test/controller/enter.information.controller.spec.unit.ts, test/controller/remove.document.controller.spec.unit.ts
Express 4 does not pass errors thrown in asynchronous calls to the global error handler.
This pr adds missing try/catch blocks to catch the errors and pass them to the error handler.
=> OBJ-235 Add try-catch to async calls to api

views/check-your-answers.html
Last fix didn’t work (a different error only showed up in pipeline a11y test not ‘wave’ locally) but I've now tested this with ‘axe’ locally and I think it will do the trick. It generates (for e-mail):
```
  <dd class=“govuk-summary-list__actions”>
    <a class=“govuk-link” href=“”>
      <span class=“govuk-visually-hidden”> email cannot be changed</span>
    </a>
  </dd> 
```
=> OBJ-292 Add visually hidden text to fix accessibility issue

src/controllers/enter.information.controller.ts, src/modules/sdk/objections/types.ts, test/controller/objecting.entity.name.controller.spec.unit.ts, test/modules/sdk/objections/service.spec.unit.ts
Fixing unit tests for objecting.entity.name.controller and added a couple more to test error page is shown if Objection name or sharedIdentity is missing.
=> OBJ-284 Updating unit tests for objecting.entity.name.controller

views/objecting-entity-name.html
Ticket at https://companieshouse.atlassian.net/browse/OBJ-308
Removed an if block in objecting-entity-name.html that was causing an error outline to appear around the name field so long as any error was present.
=> OBJ-308 error bars around unerrored fields in objecting entity name page

package-lock.json, package.json, src/services/company.filing.history.service.ts, test/services/company.filing.history.service.spec.ts
This method in service sdk currently not called, but tested and works. Ready for use when we need to retrieve the date
=> OBJ-321 Add filing history call to service sdk

src/modules/sdk/objections/service.ts, src/services/objection.service.ts, test/modules/sdk/objections/service.spec.unit.ts, test/services/objection.service.spec.unit.ts
Adding a method to the sdk/service and objection.service classes to get the company eligibility boolean from the API.
=> OBJ-324 added api call to get company eligibility

src/controllers/confirm.company.controller.ts, src/services/company.filing.history.service.ts, src/utils/date.formatter.ts, test/controller/confirm.company.controller.spec.unit.ts, test/controller/confirm.company.spec.unit.ts, test/modules/sdk/objections/service.spec.unit.ts, test/services/company.filing.history.service.spec.unit.ts, views/confirm-company.html
Checks if GAZ1 date should be displayed and if yes makes a call to get it, extract it from the response and display. If not, static text is displayed on the 'confirm' screen.
=> Obj 321 extract gaz1 date from api response

src/controllers/check.your.answers.controller.ts, test/controller/check.your.answers.controller.spec.unit.ts
If we submit an objection, go back and resubmit, the web page hangs as it doesn't deal with the error returned from the api. Adding a catch block to show the error screen rather than have the web hang.
=> OBJ-353 Fixing hanging on final submit if API returns an error

test/services/company.profile.service.spec.unit.ts
company.profile.spec.unit.ts was showing a warning that field 'links' was missing from the company profile object so this is to add it.
=> Adding missing links field to company profile test

src/controllers/check.your.answers.controller.ts, src/controllers/company.number.controller.ts, src/controllers/confirm.company.controller.ts, src/controllers/confirmation.controller.ts, src/controllers/document_upload/document.upload.controller.ts, src/controllers/document_upload/html.upload.responder.strategy.ts, src/controllers/enter.information.controller.ts, src/controllers/index.controller.ts, src/controllers/no.strike.off.controller.ts, src/controllers/notice.expired.controller.ts, src/controllers/objecting.entity.name.controller.ts, src/controllers/remove.document.controller.ts, src/modules/sdk/objections/types.ts, src/routes/routes.ts, test/controller/document_upload/html.upload.responder.strategy.spec.unit.ts, test/controller/enter.information.controller.spec.unit.ts, views/download.html, views/includes/piwik-scripts.html, views/layout.html
Moved Piwik scripts to an includes, placed that in the layout and then overwrote the layout endblock on the download.html
One thing I noticed is that for matomo to work we no longer need to pass in the templateName in the render. This is the reason download was being picked up when templateName wasn't part of the render options. We can either remove all of the templateName's from the service as part of this or raise it with Sarah as part of a future change.
=> Removing piwik scripts from download page so it wont be tracked

src/controllers/confirm.company.controller.ts, test/controller/confirm.company.controller.spec.unit.ts
Confirm this is the correct company screen will display ‘Notice expired’ if either:
EligibilityStatus.INELIGIBLE_GAZ2_REQUESTED 
EligibilityStatus.INELIGIBLE_COMPANY_STRUCK_OFF
are returned.
=> obj-447 gaz2 requested or issued show notice expired message

test/controller/notice.expired.controller.spec.unit.ts, test/routes/routes.spec.unit.ts, views/notice-expired.html
Text changes to the title and first sentence of the notice expired page. Removed the govuk-body-l class as the screenshot doesn't show the first line to be any different to the text on the rest of the page.
=> OBJ-462 amending wording on notice expired page

src/controllers/confirm.company.controller.ts, test/controller/confirm.company.controller.spec.unit.ts
Removing deleteObjectionCreate calls from the confirm company methods. The objectionCreate is still deleted later on when the customer confirms.
=> OBJ-505 error screen displays when using back button

views/confirm-company.html
Adding 'Choose a different company' link onto the confirm company screen to redirect the user back to the enter a company number screen.
Resolves: [OBJ-457](https://companieshouse.atlassian.net/browse/OBJ-457)
=> Adding choose a different company link onto the confirm company screen

views/no-strike-off.html, views/notice-expired.html
Changing feedback links for notice expired and no strike off notice pages
Resolves:
[OBJ-477](https://companieshouse.atlassian.net/browse/OBJ-477)
[OBJ-478](https://companieshouse.atlassian.net/browse/OBJ-478)
=> Changing feedback links for notice expired and no strike off notice pages

src/model/page.urls.ts, src/model/template.paths.ts, src/routes/routes.ts, views/objector-organisation.html
Creating a skeleton design page for objector type selection.
This page does not contain any functionality.
Only necessary information like route and paths added.
Resolves: [OBJ-511](https://companieshouse.atlassian.net/browse/OBJ-511)
=> Creating a skeleton design page for objector type selection

src/constants.ts, views/objecting-entity-name.html
Adding global variable onto the title of the page to successfully track in Matomo for the dynamic organisation entity name page
Resolves: [BI-7538](https://companieshouse.atlassian.net/browse/BI-7538)
=> Adding global variable onto the title of the page to successfully track in Matomo

views/index.html
A new goal ID was added from admin for the Strike Off Objections Web Start Now button (ID = 15).
Resolves: [BI-7681](https://companieshouse.atlassian.net/browse/BI-7681)
=> Correcting Matomo Goal ID for Objections Web Start Now Button

views/index.html
Reverting start now button id to 3 to be correct for live env after discussions we had with Rachel Cozens
Resolves: [BI-7681](https://companieshouse.atlassian.net/browse/BI-7681)
=> Reverting start now button id to 3 to be correct for live env

views/check-your-answers.html
Converting the first summary list for 'Your Details' into HTML instead of nunjucks to allow us to remove the hidden change link for the email address field. If we use nunjucks to create an empty action for the email address field, it will auto populate the `<a href>` which causes an accessibility violation as the link is empty.
Resolves: [BI-7713](https://companieshouse.atlassian.net/browse/BI-7713)
=> Fixing accessibility issue for check your answers screen hidden change link

src/controllers/objecting.entity.name.controller.ts, src/validation/index.ts, test/controller/enter.information.controller.spec.unit.ts, test/controller/objecting.entity.name.controller.spec.unit.ts
Adding Validation to Reason for Objection screen to ignore whitespace when checking for empty text box
=> Ignoring whitespace on objection reason screen

views/confirmation.html
Resolves: [BI-8824](https://companieshouse.atlassian.net/browse/BI-8824)
Updating the url for the survey link on the confirmation page to reflect the new survey on smartsurvey.co.uk.
=> Changing current research.net survey url link to smart survey link

views/notice-expired.html
Resolves[BI-8882](https://companieshouse.atlassian.net/browse/BI-8882)
Updating survey link on the 'notice expired' to reflect new smartsurvey url replacing research .net url
=> Updating survey link url for notice expired page

src/utils/request.util.ts, test/utils/request.util.spec.unit.ts
Resolves [DEBT-1724](https://companieshouse.atlassian.net/browse/DEBT-1724)
Adding tests and log to improve coverage of new `request.utils` class. This was added as part of the SonarQube vulnerability critical fix [DEBT-1732](https://companieshouse.atlassian.net/browse/DEBT-1732) that has been implemented previously as part of the investigation.
=> DEBT-1724 resolve critical sonar vulnerabilty allowlist urls

src/controllers/company.number.controller.ts, test/controller/company.number.controller.spec.unit.ts
Resolves [DEBT-1752](https://companieshouse.atlassian.net/browse/DEBT-1752)
Checks if the error is 404 within the string instead of the status property as it was removed to fix security vulnerabilities
=> DEBT-1752 Fix logic to correctly display the company not found page

views/signout.html
Resolves: [BI-11638](https://companieshouse.atlassian.net/browse/BI-11637)
- Update title to have the a page heading value that will register as h1 heading to prevent h1 missing alert in WAVE.
-  Amend typo in the signout radio id and fix href link in the error message to direct to the correct 'yes' radio attribute when a error is triggered
=> Improve accessibility on sign-out page

views/layout.html
Resolves: [BI-11427-](https://companieshouse.atlassian.net/browse/BI-11427) 
- Adding Matomo attribute to sign out button to register in Matomo analytics when sign-out link is pressed
=> BI-11427- Adding Matomo attribute to sign out link button

src/controllers/enter.information.controller.ts, test/controller/enter.information.controller.spec.unit.ts
Resolves [BI-11957](https://companieshouse.atlassian.net/browse/BI-11957)
- Add another call to addObjection and previously selected company to session into GET call of `enter information` page so that it is saved in session when the user traverses back to confirm company page.
- Add unit test to cover this call to set previously selected company
=> BI-11957/Stop new reports being created if company already selected

README.md
Minor docs change (numbering and table showing incorrectly in readme) so that release job will run in concourse to test pipeline change made to release task.
[Link to Jira](https://companieshouse.atlassian.net/browse/IE-301)
=> IE-301: update docs to test sbom pipeline changes
